administrative/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
        url(r'^$', views.index, name = 'reg-index'),
        url(r'^employee-list/$', views.userList, name = 'employee-list'),
        url(r'^employee-list/table$', views.tableEmployeeList, name = 'employee-table'),
        url(r'^employee-list/add$', views.addEmployeeProfile, name = 'employee-add'),
        url(r'^employee-list/create$', views.createEmployeeProfile, name = 'employee-create'),
        url(r'^employee-list/update/(?P<pk>\d+)$', views.updateEmployee, name = 'employee-update'),
        url(r'^employee-list/edit-form/(?P<pk>\d+)$', views.updateEmployeeForm, name = 'employee-update-form'),
    ]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.dashboard, name = 'dashboard'),
    url(r'^settings/', views.settings, name = 'settings'),
    url(r'^admin-reports/', views.reports, name = 'reports'),
    url(r'^registration/', include('registration.urls'), name = 'registration'),
    url(r'^cashier/', include('cashier.urls'), name = 'cashier'),
    url(r'^enrollment/', include('enrollment.urls'), name = 'enrollment'),
    url(r'^administrative/', include('administrative.urls'), name = 'administrative'),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
        url(r'^accounts/', include('django.contrib.auth.urls')),
    ]
    
'''This automatically adds:
    ^accounts/login/$ [name='login']
    ^accounts/logout/$ [name='logout']
    ^accounts/password_change/$ [name='password_change']
    ^accounts/password_change/done/$ [name='password_change_done']
    ^accounts/password_reset/$ [name='password_reset']
    ^accounts/password_reset/done/$ [name='password_reset_done']
    ^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
    ^accounts/reset/done/$ [name='password_reset_complete']
    
    
    although they dont have any templates yet, you can add each inside ./auth/templates
'''

administrative/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.core.urlresolvers import reverse
#from registration.models import Student
#from enrollment.models import School_Year

# Create your models here.

CASHIER = 'c'
REGISTRAR = 'r'
ACADEMIC_HEAD = 'h'
TEACHER = 't'
OTHERS = 'n'

ACTIVE = 'a'
INACTIVE = 'i'
ON_LEAVE = 'o'

FULL_TIME = 'f'
PART_TIME = 'p'

class Employee(models.Model):
	employee_ID = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	
	WORK_CHOICES = (
		(FULL_TIME, 'Full Time'),
		(PART_TIME, 'Part Time'),
		(OTHERS, 'Others'),
		)
	work_type = models.CharField(max_length=1,
	    choices=WORK_CHOICES,
	    blank=False,
	    default=OTHERS
	    )
	
	
	TYPE_CHOICES = (
	    (CASHIER, 'Cashier'),
	    (REGISTRAR, 'Registrar'),
	    (ACADEMIC_HEAD, 'Academic Head'),
	    (TEACHER, 'Teacher'),
	    (OTHERS, 'Others'),
	)
	emp_type = models.CharField(max_length=1,
	    choices=TYPE_CHOICES,
	    blank=False,
	    default=OTHERS
	    )

	STATUS_CHOICES = (
	    (ACTIVE, 'Active'),
	    (ON_LEAVE, 'On Leave'),
	    (INACTIVE, 'Inactive'),
	)
	emp_status = models.CharField(max_length=1,
	    choices=STATUS_CHOICES,
	    blank=False,
	    default=INACTIVE
	    )
        
	
	class Meta:
		verbose_name = "Employee"
		
	def __str__(self):
		return self.first_name
		
	def get_abosulute_url(self):
	    return reverse('employee-list', kwargs={"id": self.id})
	
ON_HOLD = "h"
APPROVED = "p"
DECLINED = "d"

class Promissory(models.Model):
	promissory_ID = models.AutoField(primary_key=True)
	promisorry_title = models.CharField(max_length=200)
	reason = models.CharField(max_length=500)
	date_filed = models.DateTimeField(null=True, blank=True, auto_now = True)
	date_approved = models.DateTimeField(null=True, blank=True, auto_now = True)
	due_of_payment = models.DateTimeField(null=True, blank=True)
	student_ID = models.ForeignKey('registration.Student', on_delete=models.CASCADE, default=0)
	schoolYr_ID = models.ForeignKey('enrollment.School_Year', on_delete=models.CASCADE, default=0)
	STATUS_CHOICES = (
	    (ON_HOLD, 'On Hold'),
	    (APPROVED, 'Approved'),
	    (DECLINED, 'Declined'),
	)
	promissory_status = models.CharField(max_length=1,
	    choices=STATUS_CHOICES,
	    blank=False,
	    default=ON_HOLD
	    )
	
	class Meta:
		verbose_name = "Promissory Note"
		
	def __str__(self):
		return self.promisorry_title

administrative/forms.py
from django import forms
from .models import *
from enrollment.models import *
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class EmployeeForms(forms.ModelForm):
    class Meta:
        model = Employee
        exclude = ('employee_ID',)

administrative/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.utils import timezone
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmployeeForms
from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from .models import *
from django.db.models import Q

@login_required
def index(request):
    pass

@login_required
def userList(request):
    return render(request, 'administrative/admin-employee-list.html')

def addEmployeeProfile(request):
    return render(request, 'administrative/admin-employee-list-add.html')

def updateEmployee(request, pk='pk'):
    instance = get_object_or_404(Employee, pk=pk)
    return render(request, 'administrative/admin-employee-list-update.html', {'instance': instance})


    
#AJAX VIEWS --------------------------------------------------------------------
from django.template.loader import render_to_string
from django.http import JsonResponse

def tableEmployeeList(request):
    employee_list = getEmployeeList(request)
    print employee_list
    #Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(employee_list, 5)
    
    try:
        employee = paginator.page(page)
    except PageNotAnInteger:
        employee = paginator.page(1)
    except EmptyPage:
        employee = paginator.page(paginator.num_pages)
        
    context = {'employee_list': employee}
    html_form = render_to_string('administrative/table-employee-list.html',
        context,
        request = request,
    )
    return JsonResponse({'html_form' : html_form})

def createEmployeeProfile(request):
    data = {'form_is_valid' : False }
    try:
        last_employee = Employee.objects.latest('employee_ID')
    except:
        last_employee = None
    if request.method == 'POST':
        form = EmployeeForms(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = EmployeeForms()
    context = {'form': form, 'employee':last_employee}
    data['html_form'] = render_to_string('administrative/forms-employee-create.html',
        context,
        request=request,
    )
    return JsonResponse(data)
    
def updateEmployeeForm(request, pk='pk'):
    instance = get_object_or_404(Employee, pk=pk)
    data = {'form_is_valid' : False }
    try:
        last_employee = Employee.objects.latest('employee_ID')
    except:
        last_employee = None
    if request.method == 'POST':
        form = EmployeeForms(request.POST, instance = instance)
        if form.is_valid():
            instance = form.save()
            instance.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = EmployeeForms(instance = instance)
    context = {'form': form, 'employee':last_employee, 'instance': instance}
    data['html_form'] = render_to_string('administrative/forms-employee-update.html',
        context,
        request=request,
    )
    return JsonResponse(data)

def getEmployeeList(request):
    search = request.GET.get('search')
    genre = request.GET.get('genre')
    isNum = True
    try:
        int(search)
    except:
        isNum = False
    if(request.GET.get('search')!= "None"):
        if( (genre == "None" or genre == "All Categories") and isNum):
            query = Employee.objects.filter(
                Q(employee_ID__contains=search)|
                Q(first_name__contains=search)|
                Q(last_name__contains=search)|
                Q(work_type__contains=search)|
                Q(emp_type__contains=search)|
                Q(emp_status__contains=search)
            )
        if(genre == "None" or genre == "All categories"):
            query = Employee.objects.filter(
                Q(employee_ID__contains=search)|
                Q(first_name__icontains=search)|
                Q(last_name__icontains=search)|
                Q(work_type__contains=search)|
                Q(emp_type__contains=search)|
                Q(emp_status__contains=search)
            )
        elif(genre == "Full Name"):
            print "name"
            query = Employee.objects.filter(
                Q(first_name__icontains=search)|
                Q(last_name__icontains=search)
            )
        elif(genre == "Employee ID" and isNum):
            print "id"
            query = Employee.objects.filter(employee_ID=search)
        elif(genre == "Employee Type"):
            query = Employee.objects.filter(emp_type=search)
        elif(genre == "Work Type"):
            query = Employee.objects.filter(work_type=search)
            if (search == ""):
                query = Employee.objects.all()
        elif(genre == "Status"):
            query = Employee.objects.filter(emp_status=search)
        elif(search == ""):
            query = Employee.objects.all()
        else:
            print "wala"
            query = Employee.objects.all() 
            
    else:
        return []
    return query
    

front-end/templates/administrative/admin-dashboard.html
<div class="container-fluid bg-dashboard">
    <div class="content container">
        <div class="content-heading margin">
            <div class="titlehead">
                <h1 class="text-center"> Maryknoll Academy of Cateel</h1>
            </div>
            <div class="link uppercase text-center">
                <h4 class="subtitle">Dashboard</h4>
            </div>
            <div class="subtitle-border"></div>
        </div>
        <div class="quick-links">
            <div class="row">
                <div class="col quick-links-item">
                    <button class="btn-links" onclick="location.href='{% url 'student-list' %}'">
                        <i class="icon-people quick-links-icons"></i>
                        <h4 class="uppercase"> Students </h4>
                    </button>
                </div>
                <div class="col quick-links-item">
                    <button class="btn-links" onclick="location.href='{% url 'employee-list' %}'">
                        <i class="icon-people quick-links-icons"></i>
                        <h4 class="uppercase"> Employees </h4>
                    </button>
                </div>
                <div class="col quick-links-item">
                    <button class="btn-links" onclick="location.href='users-list.html'">
                        <i class="icon-people quick-links-icons"></i>
                        <h4 class="uppercase"> System Users </h4>
                    </button>
                </div>
            </div>
        </div>
        <div class="quick-links">
            <div class="row">
                <div class="col quick-links-item">
                    <button class="btn-links" onclick="location.href='student-registration-list.html'">
                        <i class="icon-chart quick-links-icons"></i>
                        <h4 class="uppercase"> Daily Cash Report </h4>
                    </button>
                </div>
                <div class="col quick-links-item">
                    <button class="btn-links" onclick="location.href='employee-list.html'">
                        <i class="icon-chart quick-links-icons"></i>
                        <h4 class="uppercase"> Daily Enrollees Report </h4>
                    </button>
                </div>
                <div class="col quick-links-item">
                    <button class="btn-links" onclick="location.href='users-list.html'">
                        <i class="icon-chart quick-links-icons"></i>
                        <h4 class="uppercase"> Money Something </h4>
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

front-end/templates/administrative/admin-employee-list-add.html
{% extends 'base.html' %}
{% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %}

{%load static%}
{% block content %}
    <div class="container-fluid bg-content wrapper">
      <div class="content">
        
        </div>
       </div>
       
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
    

<script>
$(function() {
  $.ajax({
        url: '{% url "employee-create" %}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $(".content").html(data.html_form);
        }
  });
  
    $(".content").on("submit", ".js-employee-create-form", function() {
    var form = $(this);
    $.ajax({
        url: '{% url "employee-create" %}',
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
            if (data.form_is_valid) {
                window.location = "{%url 'employee-list' %}"
            }
            else {
                console.log(data.form_is_valid);
                $(".content").html(data.html_form);
            }
        }
    });
    return false;
    });
    
});


</script>

{%endblock%}

front-end/templates/administrative/admin-employee-list-update.html
{% extends 'base.html' %}
{% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %}

{%load static%}
{% block content %}
    <div class="container-fluid bg-content wrapper">
      <div class="content">
        
        </div>
       </div>
       
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

<script>
$(function() {
  $.ajax({
        url: '{% url "employee-update-form" instance.employee_ID%}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $(".content").html(data.html_form);
        }
  });
  
    $(".content").on("submit", ".js-employee-update-form", function() {
    var form = $(this);
    $.ajax({
        url: '{% url "employee-update-form" instance.employee_ID%}',
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
            if (data.form_is_valid) {
                window.location = "{%url 'employee-list' %}"
            }
            else {
                console.log(data.form_is_valid);
                $(".content").html(data.html_form);
            }
        }
    });
    return false;
    });
    
});


</script>
{%endblock%}

front-end/templates/administrative/admin-employee-list.html
{% extends 'base.html' %}
{% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %}

{%load static%}
{% block content %}
<!-- CONTENT -->
<div class="container-fluid bg-content">
      <div class="content">
        <div class="seal"></div>
        <h2> Employee Profiles </h2>
        <div class="menu-flex search-bar no-print">
          <div class="flex-search">
            <div class="input-group">
              <div class="input-group-btn">
                <button id="selected" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Category
                </button>
                <!-- Supply dropdown menu categories, refer to database -->
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">All categories</a>
                  <a class="dropdown-item" href="#">Full Name</a>
                  <a class="dropdown-item" href="#">Employee Type</a>
                  <a class="dropdown-item" href="#">Work Type</a>
                </div>
              </div>
              <input type="text" class="changeIfStatus form-control" placeholder="Search records..." aria-label="Search records...">
              <span class="input-group-btn">
                <button type="button" class="btn btn-primary">Search</button>
              </span>
            </div>
          </div>
          <div class="flex-print">
            <a href="javascript:window.print()" class="card-link btn btn-outline-primary"><i class="fa fa-print" aria-hidden="true"></i> Print Employee Records</a>
            <a href="{%url 'employee-add' %}" class="add-button btn btn-primary "><i class="fa fa-plus" aria-hidden="true"></i> Create Employee Profile</a>
          </div>
        </div>
    <div class="row table-records table-responsive" id="employee-listings">
      <!-- INSERT TABLE HERE -->
      
    </div>
  </div>
</div>
<!-- CONTENT -->

<!-- Allows dropdown menu to select child -->
<script>
var selected = "None";
var search_data = "None";
  $(function() {
    $(".dropdown-menu a").click(function() {
      $("#selected:first-child").text($(this).text());
      $("#selected:first-child").val($(this).text());
      selected = $("#selected:first-child").val();
      if ($("#selected:first-child").val() == "All categories") {
        generatePage(1)
      }
      else {
      }
    });
  });
</script>
<!-- ---------------------------BACKEND SCRIPTS ------------------------------->
<script>
$(function() {
  $.ajax({
        url: '{% url "employee-table" %}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $("#employee-listings").html(data.html_form);
        }
    });
});

function generatePage(pageNum){
    if(search_data == "None" || selected == "None"){
      generatePages(pageNum)
    }else{
      generatePages2(pageNum)
    }
  }
  function generatePages(pageNum) {
    $.ajax({
      url: '{% url "employee-table" %}?page=' + pageNum,
      type: 'get',
      dataType: 'json',
      success: function(data) {
        $("#employee-listings").html(data.html_form);
      }
    });
  }
  
  function generatePages2(pageNum) {
    $.ajax({
      url: '{% url "employee-table" %}?page=' + pageNum + '&search='+search_data+"&genre="+selected,
      type: 'get',
      dataType: 'json',
      success: function(data) {
        $("#employee-listings").html(data.html_form);
      }
    });
  }
  
 $('.search').click(function() {
    search_data = $('.search-input').val();
    if(search_data == ""){
      search_data = "None"
    }
    generateSearch();
  });
  
  function generateSearch() {
    $.ajax({
      url: '{% url "employee-table" %}?search='+search_data+"&genre="+selected,
      type: 'GET',
      dataType: 'json',
      success: function(data) {
        $("#employee-listings").html(data.html_form);
      }
    });
  }
</script>

{%endblock%}

front-end/templates/administrative/admin-settings.html
{% extends 'base.html' %} {% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %} {%block title%} Admin Settings {%endblock%}{% block content %}
<div class="container-fluid bg-content wrapper">
  <div class="content">
    <div class="content-heading margin">
      <h1>Admin Functionalities </h1> <!-- Replace with *cashier* or *registrar* or depending on the user + "functionalities" -->
      <!-- Alphabetical order -->
    </div>
    <!-- Registrar -->
    <div class="row row-menu">
      <div class="col-lg-4">
        <h3 class="link"> Student Profiles </h3>
        <a href="{%url 'student-list'%}" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Student Profiles</a>
      </div>
    </div>
    <!-- Cashier -->
    <div class="row row-menu">
      <div class="col-lg-4">
        <h3 class="link"> Fees and Accounts </h3>
        <a href="#" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Fees and Accounts</a>
      </div>
      <div class="col-lg-4">
        <h3 class="link"> Payment Logs </h3>
        <a href="#" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Fees and Accounts</a>
      </div>
      <div class="col-lg-4">
        <h3 class="link"> Student Accounts </h3>
        <a href="student-accounts.html" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Student Accounts</a><br/>
      </div>
    </div>
    <div class="row row-menu">
      <div class="col-lg-4">
        <h3 class="link"> Student Ledger </h3>
        <a href="#" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Student Ledger</a>
      </div>
    </div>
    <!-- Academic Head -->
    <div class="row row-menu">
      <div class="col-lg-4">
        <h3 class="link"> Curriculum and Subjects </h3>
        <a href="{%url 'curriculum-list'%}" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Curriculum</a><br/>
      </div>
      <div class="col-lg-4">
        <h3 class="link"> Scholarships </h3>
        <a href="{%url 'scholarship-list'%}" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Available Scholarships</a>
      </div>
      <div class="col-lg-4">
        <h3 class="link"> School Year and Offerings </h3>
        <a href="{%url 'subjectOffering-list'%}" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Subject Offerings</a><br/>
      </div>
    </div>
    <div class="row row-menu">
      <div class="col-lg-4">
        <h3 class="link"> Section </h3>
        <a href="{% url 'section-list' %}" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Sections</a><br/>
      </div>
    </div>
    <!--Administrative-->
    <div class="row row-menu">
      <div class="col-lg-4">
        <h3 class="link"> Employee Profiles</h3>
        <a href="{%url 'employee-list'%}" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Employee Profiles</a>
      </div>
    </div>
    <div class="content-heading margin">
      <h1>System Configurations </h1>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <h3 class="link">Users</h3>
        <a href="users-list.html" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Users </a><br/>
      </div>
      <div class="col-lg-4">
        <h3 class="link"> Permissions </h3>
        <a href="curriculum-subjects.html" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> Create custom permissions</a><br/>
      </div>
    </div>
  </div>
</div>

{%endblock%}

front-end/templates/administrative/forms-employee-create.html
<div class="form-heading margin">
          <h1> Settings - Employee Profile </h1>
        </div>
          {% load widget_tweaks %}
          <form action="{% url 'employee-create' %}" method="POST" class="js-employee-create-form">
          {% csrf_token %}

               <!-- Emp First Name -->
              <div class="row">
                  <label class="control-label col-sm-2" for="empFN">First Name:</label>
                  <div class="col-sm-4">
                    {{form.first_name|add_class:"form-control"|attr:"placeholder = Enter First Name"}}
                    {% if form.first_name.errors %}
                      <p class="help-block">{{ form.first_name.errors }}</p>
                    {% endif %}
                  </div>

                <!-- Emp Last Name -->
                  <label class="control-label col-sm-2" for="empLN">Last Name:</label>
                  <div class="col-sm-4">
                    {{form.last_name|add_class:"form-control"|attr:"placeholder = Enter First Name"}}
                    {% if form.last_name.errors %}
                      <p class="help-block">{{ form.last_name.errors }}</p>
                    {% endif %}
                  </div>
              </div>

              <div style="margin: 10px 10px 10px 10px"> </div>

              <div class="row">
                  <!-- Emp Username -->
                  <label class="control-label col-sm-2" for="empUN">Work Type:</label>
                  <div class="col-sm-4">
                    {{form.work_type|add_class:"form-control"|attr:"placeholder = Work Type"}}
                    {% if form.work_type.errors %}
                      <p class="help-block">{{ form.work_type.errors }}</p>
                    {% endif %}
                  </div>
                
              </div>

              <div style="margin: 10px 10px 10px 10px"> </div>

              <div class="row">
                  <div class="col-md-2">
                    <label>Employee Type:</label><br/>
                    {{form.emp_type|add_class:"form-control"}}
                    {% if form.emp_type.errors %}
                        <p class="help-block">{{ form.emp_type.errors }}</p>
                    {% endif %}
                  </div>

                  <div class="col-md-2">
                    <label>Employee Status:</label>
                    {{form.emp_status|add_class:"form-control"}}
                    {% if form.emp_status.errors %}
                        <p class="help-block">{{ form.emp_status.errors }}</p>
                    {% endif %}
                  </div>
                  
              </div>

                <hr>

                <div class="row">
                  <div class="col-md-12">
                    <div class="float-right">
                        <input type="submit" class="btn btn-primary" value="Save Employee Profile"></input> 
                    </div>
                  </div>
                </div>



          </form>

front-end/templates/administrative/forms-employee-update.html
<div class="form-heading margin">
          <h1> Settings - Employee Profile </h1>
        </div>
          {% load widget_tweaks %}
          <form action="{% url 'employee-update-form' pk=instance.employee_ID %}" method="POST" class="js-employee-update-form">
          {% csrf_token %}

               <!-- Emp First Name -->
              <div class="row">
                  <label class="control-label col-sm-2" for="empFN">First Name:</label>
                  <div class="col-sm-4">
                    {{form.first_name|add_class:"form-control"|attr:"placeholder = Enter First Name"}}
                    {% if form.first_name.errors %}
                      <p class="help-block">{{ form.first_name.errors }}</p>
                    {% endif %}
                  </div>

                <!-- Emp Last Name -->
                  <label class="control-label col-sm-2" for="empLN">Last Name:</label>
                  <div class="col-sm-4">
                    {{form.last_name|add_class:"form-control"|attr:"placeholder = Enter First Name"}}
                    {% if form.last_name.errors %}
                      <p class="help-block">{{ form.last_name.errors }}</p>
                    {% endif %}
                  </div>
              </div>

              <div style="margin: 10px 10px 10px 10px"> </div>

              <div class="row">
                  <!-- Emp Username -->
                  <label class="control-label col-sm-2" for="empUN">Work Type:</label>
                  <div class="col-sm-4">
                    {{form.work_type|add_class:"form-control"|attr:"placeholder = Work Type"}}
                    {% if form.work_type.errors %}
                      <p class="help-block">{{ form.work_type.errors }}</p>
                    {% endif %}
                  </div>
                
              </div>

              <div style="margin: 10px 10px 10px 10px"> </div>

              <div class="row">
                  <div class="col-md-2">
                    <label>Employee Type:</label><br/>
                    {{form.emp_type|add_class:"form-control"}}
                    {% if form.emp_type.errors %}
                        <p class="help-block">{{ form.emp_type.errors }}</p>
                    {% endif %}
                  </div>

                  <div class="col-md-2">
                    <label>Employee Status:</label>
                    {{form.emp_status|add_class:"form-control"}}
                    {% if form.emp_status.errors %}
                        <p class="help-block">{{ form.emp_status.errors }}</p>
                    {% endif %}
                  </div>
                  
              </div>

                <hr>

                <div class="row">
                  <div class="col-md-12">
                    <div class="float-right">
                        <input type="submit" class="btn btn-primary" value="Save Employee Profile"></input> 
                    </div>
                  </div>
                </div>



          </form>

front-end/templates/administrative/table-employee-list.html
<table class="table table-bordered bg-nav table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Employee Type</th>
      <th scope="col">Work Type</th>
      <th scope="col">Employee Status</th>
      <th scope="col" class="no-print">Actions</th>
    </tr>
  </thead>
  <tbody>
    {%for emp in employee_list%}
    <tr>
      <td>{{emp.last_name}}, {{emp.first_name}}</td>
      <td>{{emp.get_emp_type_display}}</td>
      <td>{{emp.get_work_type_display}}</td>
      <td><i class="fa fa-circle 
                  {%if emp.emp_status == " a "%}
                      active-status">
                      </i> Active</td>
      {%else%} inactive-status">
      </i> Inactive</td>
      {%endif%}
      <td class="no-print text-center">
        <a href="#" class="btn btn-success btn-sm view-button">View</a>
        <a href="{% url 'employee-update' pk=emp.employee_ID %}" class="btn btn-secondary btn-sm view-button">Edit</a></td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="5" class="text-center">No Employee</td>
    </tr>
    {%endfor%}

  </tbody>
</table>