main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.dashboard, name = 'dashboard'),
    url(r'^settings/', views.settings, name = 'settings'),
    url(r'^admin-reports/', views.reports, name = 'reports'),
    url(r'^registration/', include('registration.urls'), name = 'registration'),
    url(r'^cashier/', include('cashier.urls'), name = 'cashier'),
    url(r'^enrollment/', include('enrollment.urls'), name = 'enrollment'),
    url(r'^administrative/', include('administrative.urls'), name = 'administrative'),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
        url(r'^accounts/', include('django.contrib.auth.urls')),
    ]
    
'''This automatically adds:
    ^accounts/login/$ [name='login']
    ^accounts/logout/$ [name='logout']
    ^accounts/password_change/$ [name='password_change']
    ^accounts/password_change/done/$ [name='password_change_done']
    ^accounts/password_reset/$ [name='password_reset']
    ^accounts/password_reset/done/$ [name='password_reset_done']
    ^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
    ^accounts/reset/done/$ [name='password_reset_complete']
    
    
    although they dont have any templates yet, you can add each inside ./auth/templates
'''

administrative/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.core.urlresolvers import reverse
#from registration.models import Student
#from enrollment.models import School_Year

# Create your models here.

CASHIER = 'c'
REGISTRAR = 'r'
ACADEMIC_HEAD = 'h'
TEACHER = 't'
OTHERS = 'n'

ACTIVE = 'a'
INACTIVE = 'i'
ON_LEAVE = 'o'

FULL_TIME = 'f'
PART_TIME = 'p'

class Employee(models.Model):
	employee_ID = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	
	WORK_CHOICES = (
		(FULL_TIME, 'Full Time'),
		(PART_TIME, 'Part Time'),
		(OTHERS, 'Others'),
		)
	work_type = models.CharField(max_length=1,
	    choices=WORK_CHOICES,
	    blank=False,
	    default=OTHERS
	    )
	
	
	TYPE_CHOICES = (
	    (CASHIER, 'Cashier'),
	    (REGISTRAR, 'Registrar'),
	    (ACADEMIC_HEAD, 'Academic Head'),
	    (TEACHER, 'Teacher'),
	    (OTHERS, 'Others'),
	)
	emp_type = models.CharField(max_length=1,
	    choices=TYPE_CHOICES,
	    blank=False,
	    default=OTHERS
	    )

	STATUS_CHOICES = (
	    (ACTIVE, 'Active'),
	    (ON_LEAVE, 'On Leave'),
	    (INACTIVE, 'Inactive'),
	)
	emp_status = models.CharField(max_length=1,
	    choices=STATUS_CHOICES,
	    blank=False,
	    default=INACTIVE
	    )
        
	
	class Meta:
		verbose_name = "Employee"
		
	def __str__(self):
		return self.first_name
		
	def get_abosulute_url(self):
	    return reverse('employee-list', kwargs={"id": self.id})
	
ON_HOLD = "h"
APPROVED = "p"
DECLINED = "d"

class Promissory(models.Model):
	promissory_ID = models.AutoField(primary_key=True)
	promisorry_title = models.CharField(max_length=200)
	reason = models.CharField(max_length=500)
	date_filed = models.DateTimeField(null=True, blank=True, auto_now = True)
	date_approved = models.DateTimeField(null=True, blank=True, auto_now = True)
	due_of_payment = models.DateTimeField(null=True, blank=True)
	student_ID = models.ForeignKey('registration.Student', on_delete=models.CASCADE, default=0)
	schoolYr_ID = models.ForeignKey('enrollment.School_Year', on_delete=models.CASCADE, default=0)
	STATUS_CHOICES = (
	    (ON_HOLD, 'On Hold'),
	    (APPROVED, 'Approved'),
	    (DECLINED, 'Declined'),
	)
	promissory_status = models.CharField(max_length=1,
	    choices=STATUS_CHOICES,
	    blank=False,
	    default=ON_HOLD
	    )
	
	class Meta:
		verbose_name = "Promissory Note"
		
	def __str__(self):
		return self.promisorry_title

front-end/templates/registrar/student-profiles/forms-student-create.html
{% load widget_tweaks %}
<form method="POST" action="{% url 'student-create' %}" class="heading-label js-student-create-form">
  {% csrf_token %}

  <div class="row">
    <div class="col">
      <h3 class="link" style="margin-top: 10px;">Student Profile</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <label>Student ID:</label>
      <p class="form-control-static">000{{student.student_ID|add:"1"}}</p>
      <!--incremental-->
    </div>
    <div class="col-md-4{% if field.errors %} text-danger has-error{% endif %}">
      <label>Student level:</label>
      <br/>
      <!-- unsure with the term pa-->
      {{form.student_level|add_class:"form-control"}}
    </div>
  </div>
  <div class="row">
    <div class="col-md-4{% if form.first_name.errors %} text-danger has-error{% endif %}">
      <label>First name:</label> {{form.first_name|add_class:"form-control"}} {% if form.first_name.errors %}
      <p class="help-block">{{ form.first_name.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.middle_name.errors %} text-danger has-error{% endif %}">
      <label>Middle name:</label> {{form.middle_name|add_class:"form-control"}} {% if form.middle_name.errors %}
      <p class="help-block">{{ form.middle_name.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.last_name.errors %} text-danger has-error{% endif %}">
      <label>Last name:</label> {{form.last_name|add_class:"form-control"}} {% if form.last_name.errors %}
      <p class="help-block">{{ form.last_name.errors }}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6{% if form.birthplace.errors %} text-danger has-error{% endif %}">
      <label>Place of Birth:</label> {{form.birthplace|add_class:"form-control"}}
      <!-- Kung pwede API dito ng mga places in the Philippines and outside -->
      {% if form.birthplace.errors %}
      <p class="help-block">{{ form.birthplace.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.birthdate.errors %} text-danger has-error{% endif %}">
      <label>Date of Birth:</label>
      <br/> {{form.birthdate|add_class:"form-control"|attr:"placeholder:12/30/2000"|attr:"type:date"}} 
      {% if form.birthdate.errors%}
      <p class="help-block">{{ form.birthdate.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-2{% if form.gender.errors %} text-danger has-error{% endif %}">
      <label>Sex:</label>
      <br/> {{form.gender|add_class:"form-control"}} {% if form.gender.errors %}
      <p class="help-block">{{ form.gender.errors }}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col{% if form.home_addr.errors %} text-danger has-error{% endif %}">
      <label>Home Address:</label> {{form.home_addr|add_class:"form-control"}} {% if form.home_addr.errors %}
      <p class="help-block">{{ form.home_addr.errors }}</p>
      {% endif %}</div>
  </div>
  <div class="row">
    <div class="col{% if form.postal_addr.errors %} text-danger has-error{% endif %}">
      <label>Postal Address:</label> {{form.postal_addr|add_class:"form-control"}} {% if form.postal_addr.errors %}
      <p class="help-block">{{ form.postal_addr.errors }}</p>
      {% endif %}
    </div>
  </div>
  <h5 class="sm-headings">Parental Information </h5>
  <div class="row">
    <div class="col-md-4{% if form.f_firstname.errors %} text-danger has-error{% endif %}">
      <label>Father's First Name:</label> {{form.f_firstname|add_class:"form-control"}} {% if form.f_firstname.errors %}
      <p class="help-block">{{ form.f_firstname.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.f_middlename.errors %} text-danger has-error{% endif %}">
      <label>Father's Middle Name:</label> {{form.f_middlename|add_class:"form-control"}} {% if form.f_middlename.errors %}
      <p class="help-block">{{ form.f_middlename.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.f_lastname.errors %} text-danger has-error{% endif %}">
      <label>Father's Last Name:</label> {{form.f_lastname|add_class:"form-control"}} {% if form.f_lastname.errors %}
      <p class="help-block">{{ form.f_lastname.errors }}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-4{% if form.f_occupation.errors %} text-danger has-error{% endif %}">
      <label>Father's Occupation:</label> {{form.f_occupation|add_class:"form-control"}} {% if form.f_occupation.errors %}
      <p class="help-block">{{ form.f_occupation.errors }}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-4{% if form.m_firstname.errors %} text-danger has-error{% endif %}">
      <label>Mother's First Name:</label> {{form.m_firstname|add_class:"form-control"}} {% if form.m_firstname.errors %}
      <p class="help-block">{{ form.m_firstname.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.m_middlename.errors %} text-danger has-error{% endif %}">
      <label>Mother's Middle Name:</label> {{form.m_middlename|add_class:"form-control"}} {% if form.m_middlename.errors %}
      <p class="help-block">{{ form.m_middlename.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-4{% if form.m_lastname.errors %} text-danger has-error{% endif %}">
      <label>Mother's Last Name:</label> {{form.m_lastname|add_class:"form-control"}} {% if form.m_lastname.errors %}
      <p class="help-block">{{ form.m_lastname.errors }}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-4{% if form.m_occcupation.errors %} text-danger has-error{% endif %}">
      <label>Mother's Occupation:</label> {{form.m_occcupation|add_class:"form-control"}} {% if form.m_occcupation.errors %}
      <p class="help-block">{{ form.m_occcupation.errors }}</p>
      {% endif %}
    </div>
  </div>
  <h5 class="sm-headings">Sisters/Brothers enrolled in Maryknoll (Maximum: 5)</h5>
  <div class="row" id="addSibs">
    <div class="col-md-6">
      <label>Sibling's Name</label>
      <input type="text" class="form-control" placeholder="Last name, First name">
      <!-- Dito sana ba kay autocomplete from database records -->
    </div>
    <div class="col-md-6">
      <label>Year Graduated</label>
      <input type="text" class="form-control">
    </div>
  </div>
  <div class="row">
    <button type="button" onclick="add()" class="btn btn-link">
      <i class="fa fa-plus" aria-hidden="true"></i> Add another sibling</button>
  </div>
  <div class="row">
    <div class="col-md-6{% if form.guardian.errors %} text-danger has-error{% endif %}">
      <label>Guardian's Name</label> {{form.guardian|add_class:"form-control"}} {% if form.guardian.errors %}
      <p class="help-block">{{ form.guardian.errors }}</p>
      {% endif %}
    </div>
    <div class="col-md-6{% if form.guardian_addr.errors %} text-danger has-error{% endif %}">
      <label>Address</label> {{form.guardian_addr|add_class:"form-control"}} {% if form.guardian_addr.errors %}
      <p class="help-block">{{ form.guardian_addr.errors }}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col{% if form.last_school.errors %} text-danger has-error{% endif %}">
      <label>School Last Attended:</label> {{form.last_school|add_class:"form-control"}} {% if form.last_school.errors %}
      <p class="help-block">{{ form.last_school.errors }}</p>
      {% endif %}
    </div>
  </div>
  </div>
  <div class="btn-forms" style="display: flex; justify-content: flex-end">
    <!-- new changes 03/02 -->
    <button type="button" class="btn btn-link">Cancel</button>
    <!--Go back to records-->
    <button type="button" id="confirmModal" class="btn btn-primary" data-toggle="modal" data-target=".confirmModal">
      <i class="fa fa-check-circle" aria-hidden="true"></i> Save Student Profile</button>
    <div class="modal fade confirmModal" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog role=" document "">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirm Submission</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-4">
                <label>First Name:</label>
                <p class="form-control-static" id="firstName">Karl</p>
              </div>
              <div class="col-sm-4">
                <label>Middle Name:</label>
                <p class="form-control-static" id="middleName">Heinrich</p>
              </div>
              <div class="col-sm-4">
                <label>Last Name:</label>
                <p class="form-control-static" id="lastName">Marx</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-8">
                <label>Place of Birth:</label>
                <p class="form-control-static" id="pob">Tier, Germany Tier, Germany Tier, Germany Tier, Germany Tier, Germany</p>
              </div>
              <div class="col-sm-4">
                <label>Date of Birth:</label>
                <p class="form-control-static" id="dob">May 5, 1818</p>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <label>Home Address:</label>
                <p class="form-control-static" id="homeAdd">Tier, Germany Tier, Germany Tier, Germany Tier, Germany Tier, Germany</p>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <label>Postal Address:</label>
                <p class="form-control-static" id="homeAdd">Tier, Germany Tier, Germany Tier, Germany Tier, Germany Tier, Germany</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-4">
                <label>Father's First Name:</label>
                <p class="form-control-static" id="fFirstName">Iosif</p>
              </div>
              <div class="col-sm-4">
                <label>Father's Middle Name:</label>
                <p class="form-control-static" id="fMidName">Vissarionovich </p>
              </div>
              <div class="col-sm-4">
                <label>Father's Last Name:</label>
                <p class="form-control-static" id="fLastName">Dzhugashvili</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-4">
                <label>Mother's First Name:</label>
                <p class="form-control-static" id="mFirstName">Hillary</p>
              </div>
              <div class="col-sm-4">
                <label>Mother's Middle Name:</label>
                <p class="form-control-static" id="mMidName">Diane</p>
              </div>
              <div class="col-sm-4">
                <label>Mother's Last Name:</label>
                <p class="form-control-static" id="mLastName">Clinton</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <label>Sibling Full Name:</label>
                <p class="form-control-static" id="sFullName">Putin, Vladimir</p>
              </div>
              <div class="col-sm-4">
                <label>Year Graduated:</label>
                <p class="form-control-static" id="yrGrad">2018</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <label>Guardian's Full Name:</label>
                <p class="form-control-static" id="gFullName">Trump, Donald John</p>
              </div>
              <div class="col-sm-6">
                <label>Guardian's Address:</label>
                <p class="form-control-static" id="mMidName">Pyongyang, North Korea</p>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <label>School Last Attended:</label>
                <p class="form-control-static" id="mFirstName">Florida High School</p>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="buttSubmit" > Submit Student Profile</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script>
  var count = 1;
  var add = function () {
    if (count >= 5) return;
    $('#addSibs').append('<div class="col-md-6"> <label>Sibling\'s Name</label><input type="text" class="form-control" placeholder="Last name, First name"></div><div class="col-md-6"><label>Year Graduated</label><input type="text" class="form-control" required></div>')
    count++;
  };
</script>

{# BACKEND SCRIPTS #}
<script>
  $('#confirmModal').click(function(){
    fillFields();
    
  });
  $('#buttSubmit').click(function(){
    $('.modal').modal('hide')
  });
  $('.modal').on('hidden.bs.modal', function () {
    $('.js-student-create-form').submit()
  })
  function fillFields(){
    $('#firstName').html($('#id_first_name').val())
  }
  
</script>

front-end/templates/registrar/student-profiles/forms-student-edit.html
{% load widget_tweaks %}
<form method="POST" action="{% url 'student-edit-form' pk=instance.pk%}" class="heading-label js-student-edit-form">
{% csrf_token %}
    
        <div class="row">
          <div class="col">
            <h3 class="link" style="margin-top: 10px;">Student Information</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
          <label>Student ID:</label>
            <p class="form-control-static">000{{student.student_ID|add:"1"}}</p><!--incremental-->
          </div>
          <div class="col-md-4{% if field.errors %} text-danger has-error{% endif %}">
            <label>Student level:</label><br/><!-- unsure with the term pa-->
            {{form.student_level|add_class:"form-control"}}
          </div>
        </div>
        <div class="row">
          <div class="col-md-10">
            <label>Student Profile Picture:</label><br>
            <label class="custom-file profile-picture">
            <input type="file" id="file" class="custom-file-input">
            <span class="custom-file-control"></span>
            </label>
          </div>
          
        </div>
        <div class="row">
          <div class="col-md-4{% if form.first_name.errors %} text-danger has-error{% endif %}">
            <label>First name:</label>
              {{form.first_name|add_class:"form-control"}}
              {% if form.first_name.errors %}
                <p class="help-block">{{ form.first_name.errors }}</p>
              {% endif %}
          </div>
          <div class="col-md-4{% if form.middle_name.errors %} text-danger has-error{% endif %}">
            <label>Middle name:</label>
              {{form.middle_name|add_class:"form-control"}}
              {% if form.middle_name.errors %}
                <p class="help-block">{{ form.middle_name.errors }}</p>
              {% endif %}
          </div>
          <div class="col-md-4{% if form.last_name.errors %} text-danger has-error{% endif %}">
            <label>Last name:</label>
              {{form.last_name|add_class:"form-control"}}
              {% if form.last_name.errors %}
                <p class="help-block">{{ form.last_name.errors }}</p>
              {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-6{% if form.birthplace.errors %} text-danger has-error{% endif %}">
            <label>Place of Birth:</label>
            {{form.birthplace|add_class:"form-control"}}
            <!-- Kung pwede API dito ng mga places in the Philippines and outside -->
            {% if form.birthplace.errors %}
                <p class="help-block">{{ form.birthplace.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-4{% if form.birthdate.errors %} text-danger has-error{% endif %}">
            <label>Date of Birth:</label><br/>
            {{form.birthdate|add_class:"form-control"}}
            {% if form.birthdate.errors %}
                <p class="help-block">{{ form.birthdate.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-2{% if form.gender.errors %} text-danger has-error{% endif %}">
            <label>Gender:</label><br/>
            {{form.gender|add_class:"form-control"}}
            {% if form.gender.errors %}
                <p class="help-block">{{ form.gender.errors }}</p>
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col{% if form.home_addr.errors %} text-danger has-error{% endif %}">
            <label>Home Address:</label>
            {{form.home_addr|add_class:"form-control"}}  
            {% if form.home_addr.errors %}
                <p class="help-block">{{ form.home_addr.errors }}</p>
            {% endif %}</div>
        </div>
        <div class="row">
          <div class="col{% if form.postal_addr.errors %} text-danger has-error{% endif %}">
            <label>Postal Address:</label>
            {{form.postal_addr|add_class:"form-control"}}
            {% if form.postal_addr.errors %}
                <p class="help-block">{{ form.postal_addr.errors }}</p>
            {% endif %}
          </div>
        </div>
        <h5 class="sm-headings">Parental Information </h5>
        <div class="row">
          <div class="col-md-4{% if form.f_firstname.errors %} text-danger has-error{% endif %}">
            <label>Father's First Name:</label>
            {{form.f_firstname|add_class:"form-control"}}
            {% if form.f_firstname.errors %}
                <p class="help-block">{{ form.f_firstname.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-4{% if form.f_middlename.errors %} text-danger has-error{% endif %}">
            <label>Father's Middle Name:</label>
            {{form.f_middlename|add_class:"form-control"}}
            {% if form.f_middlename.errors %}
                <p class="help-block">{{ form.f_middlename.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-4{% if form.f_lastname.errors %} text-danger has-error{% endif %}">
            <label>Father's Last Name:</label>
            {{form.f_lastname|add_class:"form-control"}}
            {% if form.f_lastname.errors %}
                <p class="help-block">{{ form.f_lastname.errors }}</p>
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4{% if form.f_occupation.errors %} text-danger has-error{% endif %}">
            <label>Father's Occupation:</label>
            {{form.f_occupation|add_class:"form-control"}}
            {% if form.f_occupation.errors %}
                <p class="help-block">{{ form.f_occupation.errors }}</p>
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4{% if form.m_firstname.errors %} text-danger has-error{% endif %}">
            <label>Mother's First Name:</label>
            {{form.m_firstname|add_class:"form-control"}}
            {% if form.m_firstname.errors %}
                <p class="help-block">{{ form.m_firstname.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-4{% if form.m_middlename.errors %} text-danger has-error{% endif %}">
            <label>Mother's Middle Name:</label>
            {{form.m_middlename|add_class:"form-control"}}
            {% if form.m_middlename.errors %}
                <p class="help-block">{{ form.m_middlename.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-4{% if form.m_lastname.errors %} text-danger has-error{% endif %}">
            <label>Mother's Last Name:</label>
            {{form.m_lastname|add_class:"form-control"}}
            {% if form.m_lastname.errors %}
                <p class="help-block">{{ form.m_lastname.errors }}</p>
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4{% if form.m_occcupation.errors %} text-danger has-error{% endif %}">
            <label>Mother's Occupation:</label>
            {{form.m_occcupation|add_class:"form-control"}}
            {% if form.m_occcupation.errors %}
                <p class="help-block">{{ form.m_occcupation.errors }}</p>
            {% endif %}
          </div>
        </div>
        <h5 class="sm-headings">Sisters/Brothers enrolled in Maryknoll (Maximum: 5)</h5>
        <div class="row" id="addSibs">
          <div class="col-md-6">
            <label>Sibling's Name</label>
            <input type="text" class="form-control" placeholder="Last name, First name">
            <!-- Dito sana ba kay autocomplete from database records -->
          </div>
          <div class="col-md-6">
            <label>Year Graduated</label>
              <input type="text" class="form-control">
          </div>
        </div>
        <div class="row">
          <button type="button" onclick="add()" class="btn btn-link"><i class="fa fa-plus" aria-hidden="true"></i> Add another sibling</button>
        </div>
        <div class="row">
          <div class="col-md-6{% if form.guardian.errors %} text-danger has-error{% endif %}">
            <label>Guardian's Name</label>
            {{form.guardian|add_class:"form-control"}}
            {% if form.guardian.errors %}
                <p class="help-block">{{ form.guardian.errors }}</p>
            {% endif %}
          </div>
          <div class="col-md-6{% if form.guardian_addr.errors %} text-danger has-error{% endif %}">
            <label>Address</label>
            {{form.guardian_addr|add_class:"form-control"}}
            {% if form.guardian_addr.errors %}
                <p class="help-block">{{ form.guardian_addr.errors }}</p>
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col{% if form.last_school.errors %} text-danger has-error{% endif %}">
            <label>School Last Attended:</label>
            {{form.last_school|add_class:"form-control"}}
            {% if form.last_school.errors %}
                <p class="help-block">{{ form.last_school.errors }}</p>
            {% endif %}
          </div>
          </div>
    </div>
  <div class="modal-footer">
      <a href="{%url 'student-list' %}"> <button type="button" class="btn btn-link" >Cancel</button> </a>
      <button type="submit" class="btn btn-primary">Save student profile</button>
  </div>
  </form>

front-end/templates/registrar/student-profiles/student-registration-list-add.html
{% extends 'base.html' %}
{%block title%} Student Profile {%endblock%}
{% block settings %}
<li class="nav-item active">
    <a class="nav-link" href="{% url 'settings' %}">Settings
        <span class="sr-only">(current)</span>
    </a>
</li>
{% endblock %}
{%load static%}
{% block content %}
<!-- FORM CONTENT -->
<div class="container-fluid bg-content">
  <div class="content container">
    
  </div>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
<script>
  var count=1;
  var add = function(){
    if(count >= 5) return;
    $('#addSibs').append('<div class="col-md-6"> <label>Sibling\'s Name</label><input type="text" class="form-control" placeholder="Last name, First name"></div><div class="col-md-6"><label>Year Graduated</label><input type="text" class="form-control" required></div>')
    count++;
  };
</script>
<script>
$(function() {
  $.ajax({
        url: '{% url "student-create" %}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $(".content").html(data.html_form);
        }
  });
  
});
  $(".content").on("submit", ".js-student-create-form", function() {
    
    var form = $(this);
    $.ajax({
        url: '{% url "student-create" %}',
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
            if (data.form_is_valid) {
                window.location = "{%url 'student-list'%}"
            }
            else {
                console.log(data.form_is_valid);
                $(".content").html(data.html_form);
            }
        }
    });
    
    return false;
});


</script>
{%endblock%}

front-end/templates/registrar/student-profiles/student-registration-list-update.html
{% extends 'base.html' %}
{%block title%} Admin Settings {%endblock%}
{% block settings %}
<li class="nav-item active">
    <a class="nav-link" href="{% url 'settings' %}">Settings
        <span class="sr-only">(current)</span>
    </a>
</li>
{% endblock %}
{%load static%}
{% block content %}
<!-- FORM CONTENT -->
<div class="container-fluid bg-content">
  <div class="content">
    
  </div>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
    
<script>
$(function() {
  $.ajax({
        url: '{% url "student-edit-form" pk=instance.pk %}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $(".content").html(data.html_form);
        }
  });
  
  $(".content").on("submit", ".js-student-edit-form", function() {
    
    var form = $(this);
    $.ajax({
        url: '{% url "student-edit-form" pk=instance.pk %}',
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
            if (data.form_is_valid) {
                window.location = "{%url 'student-list'%}"
            }
            else {
                console.log(data.form_is_valid);
                $(".content").html(data.html_form);
            }
        }
    });
    return false;
});
});


</script>
{%endblock%}