enrollment/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
        url(r'^section/list/details$', views.sectionDetails, name = 'section-details'),
        url(r'^$', views.index, name = 'reg-index'),
        #-----------------------CURRICULUM---------------------------------------------------------
        url(r'^curriculum-list/$', views.curriculumList, name = 'curriculum-list'),
        url(r'^curriculum-list/table$', views.tableCurriculumList, name = 'curriculum-table'),
        url(r'^curriculum-list/add$', views.addCurriculumProfile, name = 'curriculum-add'),
        url(r'^curriculum-list/create/(?P<pk>\d+)$', views.createCurriculumProfile, name = 'curriculum-create'),
        url(r'^curriculum-list/update/(?P<pk>\d+)$', views.updateCurriculum, name = 'curriculum-update'),
        url(r'^curriculum-list/edit-form/(?P<pk>\d+)$', views.editCurriculumForm, name = 'curriculum-edit-form'),
        #CURR DETAIL
        url(r'^curriculum-list/(?P<pk>\d+)/$', views.curriculumDetails, name = 'curriculum-detail'),
        url(r'^curriculum-list/subject-table/(?P<pk>\d+)$', views.tableCurriculumSubjectList, name = 'subject-table'),
        url(r'^curriculum-list/subject/add/(?P<pk>\d+)$', views.openCurriculumSubjectAdd, name = 'subject-add'),
        
        url(r'^curriculum-list/subject/edit/(?P<pk>\d+)$', views.editSubject, name = 'subject-edit'),
        url(r'^curriculum-list/subject/edit-form/(?P<pk>\d+)$', views.form_editSubject, name = 'subject-edit-form'),
        #-----------------------SECTION------------------------------------------------------------
        url(r'^section-list$', views.sectionList, name = 'section-list'),
        url(r'^section-list/table$', views.sectionTable, name = 'section-table'),
        url(r'^section-list/add$', views.addSection, name = 'section-create'),
        url(r'^section-list/add-form$', views.generateSectionForm, name = 'section-create-form'),
        
        url(r'^section-list/edit/(?P<pk>\d+)$', views.editSection, name = 'section-edit'),
        url(r'^section-list/edit-form/(?P<pk>\d+)$', views.form_editSection, name = 'section-edit-form'),
        
        url(r'^section-list/(?P<pk>\d+)/$', views.sectionDetails, name = 'section-detail'),
        url(r'^section-list/detail-table/(?P<pk>\d+)$', views.tableSectionDetail, name = 'section-detail-table'),
        url(r'^section-list/section-detail-add/(?P<pk>\d+)$', views.sectionDetailAdd, name = 'section-detail-add'),
        url(r'^section-list/section-detail-form/(?P<pk>\d+)$', views.sectionDetailFormAutoComp.as_view(), name = 'section-detail-form'),
        
        #-----------------------SCHOLARSHIP--------------------------------------------------------
        url(r'^scholarship-list/$', views.scholarshipList, name = 'scholarship-list'),
        url(r'^scholarship-list/table$', views.tableScholarshipList, name = 'scholarship-table'),
        url(r'^scholarship-list/add$', views.addScholarshipProfile, name = 'scholarship-add'),
        url(r'^scholarship-list/create$', views.createScholarshipProfile, name = 'scholarship-create'),
        
        url(r'^scholarship-list/update/(?P<pk>\d+)$', views.updateScholarship, name = 'scholarship-update'),
        url(r'^scholarship-list/edit-form/(?P<pk>\d+)$', views.editScholarshipForm, name = 'scholarship-edit-form'),
        #-----------------------SUBJECT OFFERING----------------------------------------------------
        url(r'^school-year/create$', views.newSchoolYear, name = 'create-schoolyear'),
        url(r'^subjectOffering-list/(?P<pk>\d+)$', views.subjectOfferingList, name = 'subjectOffering-list'),
        url(r'^subjectOffering-list/table/(?P<pk>\d+)$', views.tableSubjectOfferingList, name = 'subjectOffering-table'),
        url(r'^subjectOffering-list/add/(?P<pk>\d+)$', views.addSubjectOfferingProfile, name = 'subjectOffering-add'),
        url(r'^subjectOffering-list/create/(?P<pk>\d+)$', views.createSubjectOfferingProfile, name = 'subjectOffering-create'),
        url(r'^subjectOffering-list/(?P<pk>\d+)/$', views.subjectOfferingDetail, name = 'subjectOffering-detail'),
        
        url(r'^subjectOffering-list/update/(?P<pk>\d+)$', views.updateSubjectOffering, name = 'subjectOffering-update'),
        url(r'^subjectOffering-list/edit-form/(?P<pk>\d+)$', views.editSubjectOfferingForm, name = 'subjectOffering-edit-form'),
    ]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.dashboard, name = 'dashboard'),
    url(r'^settings/', views.settings, name = 'settings'),
    url(r'^admin-reports/', views.reports, name = 'reports'),
    url(r'^registration/', include('registration.urls'), name = 'registration'),
    url(r'^cashier/', include('cashier.urls'), name = 'cashier'),
    url(r'^enrollment/', include('enrollment.urls'), name = 'enrollment'),
    url(r'^administrative/', include('administrative.urls'), name = 'administrative'),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
        url(r'^accounts/', include('django.contrib.auth.urls')),
    ]
    
'''This automatically adds:
    ^accounts/login/$ [name='login']
    ^accounts/logout/$ [name='logout']
    ^accounts/password_change/$ [name='password_change']
    ^accounts/password_change/done/$ [name='password_change_done']
    ^accounts/password_reset/$ [name='password_reset']
    ^accounts/password_reset/done/$ [name='password_reset_done']
    ^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
    ^accounts/reset/done/$ [name='password_reset_complete']
    
    
    although they dont have any templates yet, you can add each inside ./auth/templates
'''

enrollment/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
import datetime
#import registration
#import administrative

# Create your models here.

ACTIVE = 'a'
ON_LEAVE = 'o'
INACTIVE = 'i'

ESC = 'e'
OTHERS = 't'

class TeacherDetails(models.Model):
    teacher_ID = models.AutoField(primary_key=True)
    employee_name = models.ForeignKey('administrative.Employee', on_delete= models.SET_NULL, null = True)
    units = models.IntegerField()
    class Meta:
        verbose_name = "Details of Teacher"
        
    def __str__(self):
        return str(self.employee_name)



class YearLevel(models.Model):
    grade_level = models.CharField(max_length=200)
    
    def __str__(self):
        return self.grade_level


class Curriculum(models.Model):
    curriculum_ID = models.AutoField(primary_key=True)
    curriculum_year = models.DateField(default=datetime.date.today)
    STATUS_CHOICES=(
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    )
    curriculum_status = models.CharField(max_length=1,
        choices=STATUS_CHOICES,
        blank=False,
        default=INACTIVE
        )
    class Meta:
        verbose_name = "Curriculum"
    def get_year(self):
        return self.curriculum_year.year
    def __str__(self):
        return "%s" % (self.curriculum_year)
        
    def get_abosulute_url(self):
	    return reverse('curriculum-list', kwargs={"id": self.curriculum_ID})

class School_Year(models.Model):
    year_name = models.CharField(max_length=200)
    date_start = models.DateField(auto_now = True)
    curriculum = models.ForeignKey(Curriculum, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "School Year"
    def get_year(self):
        return self.date_start.year
    def __str__(self):
        return self.year_name

class Scholarship(models.Model):
    scholarship_name = models.CharField(max_length=200)
    scholarship_type = models.CharField(max_length=50)
    fee_amount = models.FloatField()
    school_year = models.ForeignKey(School_Year, on_delete=models.CASCADE, default=0)  

    SCHOLARSHIP_CHOICES = (
        (ESC, 'ESC'),
        (OTHERS, 'Others'),
    )
    scholarship_type = models.CharField(max_length=1,
        choices=SCHOLARSHIP_CHOICES,
        blank=False,
        default=OTHERS
        )

    class Meta:
        verbose_name = "Scholarship"
        
    def __str__(self):
        return "%s for %s" % (self.scholarship_name, self.school_year)
class Subjects(models.Model):
    subject_ID = models.AutoField(primary_key=True)
    subject_name = models.CharField(max_length=200)
    units = models.IntegerField(null = True)
    curriculum = models.ForeignKey(Curriculum, on_delete = models.SET_NULL, null = True)
    year = models.ForeignKey(YearLevel, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "Subject"
        
    def __str__(self):
        return self.subject_name
        
	
 
class Section(models.Model):
    section_ID = models.AutoField(primary_key=True)
    section_name = models.CharField(max_length=50)
    section_capacity = models.IntegerField()
    adviser = models.ForeignKey(TeacherDetails, on_delete = models.CASCADE)
    curriculum = models.ForeignKey(Curriculum, on_delete = models.SET_NULL, null = True)
    room = models.CharField(max_length=50)
    #Section status
    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    )
    section_status = models.CharField(max_length=1,
        choices=STATUS_CHOICES,
        blank=False,
        default=INACTIVE
        )
        
    class Meta:
        verbose_name = "Section"
    def __str__(self):
        return "%s - %s" % (self.curriculum,self.section_name)
    
    def get_abosulute_url(self):
	    return reverse('section-detail', kwargs={"id": self.section_ID})
        
class Offering(models.Model):
	offering_ID = models.AutoField(primary_key=True)
	subject = models.ForeignKey(Subjects, on_delete=models.CASCADE, default=0)
	teacher = models.ForeignKey(TeacherDetails, on_delete=models.CASCADE, default=0)
	school_year = models.ForeignKey(School_Year, on_delete=models.CASCADE, default=0)
	year_level = models.ForeignKey(YearLevel, on_delete=models.CASCADE, null = True)
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null = True)
	
	class Meta:
	    verbose_name = "Offered Subject"
	def __str__(self):
	    return "%s - - - %s" % (self.subject, self.section)
	 
	def get_abosulute_url(self):
	    return reverse('subjectOffering-list', args=[str(self.offering_ID)])
	    
''' SCHEDULING WILL BE DEVELOPED IN A DIFFERENT APP '''
        
class Section_Offerings(models.Model):
	sectionDetails_ID = models.AutoField(primary_key=True)
	section_ID = models.ForeignKey(Section, on_delete=models.CASCADE, default=0)
	offering_ID = models.ForeignKey(Offering, on_delete=models.CASCADE, default=0)
	
	class Meta:
	    verbose_name = "Section Detail"
	    
	def __str__(self):
	    return "%s - %s" % (self.section_ID, self.offering_ID)
    
class SHS_Subjects(models.Model):
    s_subjectName  = models.CharField(max_length=200)
    s_subjectDesc = models.CharField(max_length=200)
    s_desc = models.CharField(max_length=100)
    s_curriculum = models.ForeignKey(Curriculum, on_delete = models.CASCADE)
    #SHS track status
    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    )
    s_status = models.CharField(max_length=1,
        choices=STATUS_CHOICES,
        blank=False,
        default=INACTIVE
        )
        
    class Meta:
        verbose_name = "Senior High Subject"
        
    def __str__(self):
        return self.s_subjectName
        
        
class SHS_Offering(models.Model):
    offering_ID = models.AutoField(primary_key=True)
    subject = models.ForeignKey(SHS_Subjects, on_delete=models.CASCADE, default=0)
    teacher = models.ForeignKey(TeacherDetails, on_delete=models.CASCADE, default=0)
    school_year = models.ForeignKey(School_Year, on_delete=models.CASCADE, default=0)
	
    class Meta:
        verbose_name = "Offered Subjects for SHS"
    def __str__(self):
        return "%s - - - %s" % (self.subject, self.offering_ID)

enrollment/forms.py
from django import forms
from .models import *
from enrollment.models import *

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

ACTIVE = 'a'
ON_LEAVE = 'o'
INACTIVE = 'i'
STATUS_CHOICES = (
    (ACTIVE, 'Active'),
    (INACTIVE, 'Inactive'),
)
class SectionForms(forms.ModelForm):
    class Meta:
        model = Section
        exclude = ('section_ID', 'section_status',)
        
class SubjectForm(forms.ModelForm):
    """Curriculum-details-create."""

    class Meta:
        """Meta definition for Subjectform."""

        model = Subjects
        exclude = ('curriculum',)

        
class ScholarshipForms(forms.ModelForm):
    class Meta:
        model = Scholarship
        exclude = ('pk',)
        
class SubjectOfferingForms(forms.ModelForm):
    class Meta:
        model = Offering
        exclude = ('pk','school_year')

class School_YearForm(forms.ModelForm):
    """Form definition for School_Year."""

    class Meta:
        """Meta definition for School_Yearform."""

        model = School_Year
        exclude = ('date_start',)

front-end/templates/enrollment/admin-settings.html
{% extends 'base.html' %} {% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %} {%block title%} Admin Settings {%endblock%}{% block content %}
<div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-faded bg-nav">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#"></a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="cashier-dashboard.html">Home </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="cashier-settings.html" style="color: #4688F1;">Settings<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Reports</a>
            </li>
          </ul>
        </div>
        <span class="navbar-text">Steve Harrington <i class="icon-arrow-down"></i> </span> <!-- User's fullname -->
        <a href="index.html">
          <button class="btn-logout"><span>Logout</span></button>
        </a>
      </nav>
    </div>
    <div class="container-fluid bg-content wrapper">
      <div class="content">
        <div class="content-heading margin">
          <h1> Cashier Functionalities </h1>
        </div>

        <div class="row row-menu">
          <div class="col-lg-4">
            <h3 class="link"> Fees and Accounts </h3>
            <a href="cashier-fees-and-accounts.html" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Fees and Accounts </a>
          </div>
        </div>

        <div class="row row-menu">
          <div class="col-lg-4">
            <h3 class="link"> Promissory Note Request</h3>
            <a href="cashier-promissory-list.html" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Promissory Note Requests</a> <br/> 
          </div>
        </div>

        <div class="row row-menu">
          <div class="col-lg-4">
            <h3 class="link"> Scholarships </h3>
            <a href="scholarship-list.html" class="grey"> <i class="fa fa-user" aria-hidden="true"></i> View Scholarship List </a>
          </div>
        </div>
{%endblock%}

front-end/templates/enrollment/curriculum-list-add.html
{% extends 'base.html' %}
{% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %}

{%load static%}
{% block content %}
    <!-- FORM CONTENT -->
    <div class="container-fluid bg-content">
      <div class="content">
        Hello
        </div>
      </div>
    </div>

<script>
  var count=1;
  var add = function(){
    if(count >= 15) return;
    $('#addSubjects').append('<div class="row" id="addSubjects"><div class="col-md-4"> <label>Subject ID:</label><p class="form-control-static">0001</p></div><div class="col-md-6"><label>Subject Name:</label><input type="text" class="form-control" required></div><div class="col-md-2 text-center delete-btn"><a href="#" class="delete-row warning" onclick="deleteRow(this)"><i class="fa fa-close"></i></div></div>') // Increment SubjectID
    count++;
  };
</script>

<script>
  function deleteRow(obj){
    $(obj).closest('.row').remove();
  }
</script>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
<!------------------------------------------------------------------------------>
<script>
$(function() {
  $.ajax({
        url: '{% url "curriculum-create" curriculum.curriculum_ID %}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $(".content").html(data.html_form);
        }
  });
  
  $(".content").on("submit", ".js-subject-create-form", function() {
    var form = $(this);
    $.ajax({
        url: '{% url "curriculum-create" curriculum.curriculum_ID %}',
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
            if (data.form_is_valid) {
                window.location = "{%url 'curriculum-detail' curriculum.curriculum_ID %}"
            }
            else {
                console.log(data.form_is_valid);
                $(".content").html(data.html_form);
            }
        }
    });
    return false;
});
});


</script>
{%endblock%}

front-end/templates/enrollment/curriculum-list-update.html
{% extends 'base.html' %}
{% block settings %}
<li class="nav-item active-menu">
  <a class="nav-link" href="{% url 'admin-settings' %}" style="color: #4688F1;">Settings</a>
</li>
{% endblock %}

{%load static%}
{% block content %}
    <!-- FORM CONTENT -->
    <div class="container-fluid bg-content">
      <div class="content">
        
        </div>
      </div>
    </div>

<script>
  var count=1;
  var add = function(){
    if(count >= 15) return;
    $('#addSubjects').append('<div class="row" id="addSubjects"><div class="col-md-4"> <label>Subject ID:</label><p class="form-control-static">0001</p></div><div class="col-md-6"><label>Subject Name:</label><input type="text" class="form-control" required></div><div class="col-md-2 text-center delete-btn"><a href="#" class="delete-row warning" onclick="deleteRow(this)"><i class="fa fa-close"></i></div></div>') // Increment SubjectID
    count++;
  };
</script>

<script>
  function deleteRow(obj){
    $(obj).closest('.row').remove();
  }
</script>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
<!------------------------------------------------------------------------------>
<script>
$(function() {
  $.ajax({
        url: '{% url "curriculum-edit-form" pk=instance.pk %}',
        type: 'get',
        dataType: 'json',
        success: function(data) {
            $(".content").html(data.html_form);
        }
  });
  
  $(".content").on("submit", ".js-curriculum-edit-form", function() {
    var form = $(this);
    $.ajax({
        url: '{% url "curriculum-edit-form" pk=instance.pk %}',
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
            if (data.form_is_valid) {
                window.location = "{%url 'curriculum-list' %}"
            }
            else {
                console.log(data.form_is_valid);
                $(".content").html(data.html_form);
            }
        }
    });
    return false;
});
});


</script>
{%endblock%}

front-end/templates/enrollment/forms-curriculum-edit.html
{% load widget_tweaks %}
<form action="{% url 'curriculum-edit-form' pk=instance.curriculum_ID %}" method="POST" class="js-curriculum-edit-form">
{% csrf_token %}
<div class="row">
    <div class="col">
      <h3 class="link" style="margin-top: 10px;">New Curriculum</h3>
        </div>
    </div>
    <div class="row">
      <div class="col-md-4">
      <label>Curriculum ID:</label>
        <p class="form-control-static">0001</p><!--incremental-->
      </div>
      <div class="col-md-4">
        <label>School Year:</label><br/>
        {{form.school_year|add_class:"form-control"|attr:"placeholder = Scholarship Type"}}
            {% if form.school_year.errors %}
              <p class="help-block">{{ form.school_year.errors }}</p>
            {% endif %}
      </div>
      <div class="col-md-4">
        <label>Year Level:</label><br/>
        {{form.year_level|add_class:"form-control"|attr:"placeholder = Scholarship Type"}}
            {% if form.year_level.errors %}
              <p class="help-block">{{ form.year_level.errors }}</p>
            {% endif %}
      </div>
      
    </div>
    <div class="btn-forms" style="display: flex; justify-content: flex-end">
      <a href="curriculum-list.html" class="btn btn-link">Cancel</a>
       <input type="submit" class="btn btn-primary" value="Save Curriculum Details"></input>
    </div>
</form>

front-end/templates/enrollment/forms-curriculum-subjects-list-create.html
{% load widget_tweaks %}
<form action="{% url 'curriculum-create' curriculum.curriculum_ID  %}" method="POST" class="js-subject-create-form">
    {% csrf_token %}
      <div class="row">
        <div class="col">
          <h3 class="link" style="margin-top: 10px;">Subject Details</h3>
        </div>
      </div>
        <div class="row">
          <div class="col-md-4">
            <label>Year Level:</label>
            {{form.year|add_class:"custom-select btn-block"}}
          </div>
        </div>
        <div id="addSubjects">
          <div class="row">
            <div class="col-md-2">
              <label>Subject ID:</label>
              <p class="form-control-static">000{{curriculum.pk|add:"1"}}</p>
            </div>
            <div class="col-md-6">
              <label>Subject Name:</label>
                {{form.subject_name|add_class:"form-control"}}
            </div>
            <div class="col-md-2">
              <label>Units:</label>
              {{form.units|add_class:"form-control"}}
            </div>
            <div class="col-md-2 text-center delete-btn">
              <a href="#" class="delete-row warning" onclick="deleteRow(this)"><i class="fa fa-close"></i></a>
            </div>
          </div>
        </div>
        <div class="row">
          <button type="button" onclick="add()" class="btn btn-link"><i class="fa fa-plus" aria-hidden="true"></i> Add additional subjectss</button>
        </div>
        <div class="btn-forms" style="display: flex; justify-content: flex-end">
              <a href="{%url 'curriculum-detail' curriculum.curriculum_ID %}" class="btn btn-link">Cancel</a>
              <button type="submit" class="btn btn-primary "><i class="fa fa-check-circle" aria-hidden="true"></i> Save Curriculum Details</button>
        </div>
    </div>
  </div>
</form>

front-end/templates/enrollment/forms-scholarship-edit.html
{% load widget_tweaks %}
  <form action="{% url 'scholarship-edit-form' pk=instance.pk %}" method="POST" class="js-scholarship-edit-form">
{% csrf_token %}
    <div class="row">
      <div class="col">
        <h3 class="link" style="margin-top: 10px;">Scholarship Details</h3>
          </div>
      </div>
        <div class="row">
          <div class="col-md-4">
          <label>Scholarship ID:</label>
            <p class="form-control-static">0002</p><!--incremental-->
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>Scholarship Name:</label>
            {{form.scholarship_name|add_class:"form-control"|attr:"placeholder = Enter First Name"}}
                    {% if form.scholarship_name.errors %}
                      <p class="help-block">{{ form.scholarship_name.errors }}</p>
                    {% endif %}
          </div>
          
        </div>
        <div class="row">
          <div class="col-md-4">
            <label>Scholarship Type:</label>
            {{form.scholarship_type|add_class:"form-control"|attr:"placeholder = Scholarship Type"}}
                    {% if form.scholarship_type.errors %}
                      <p class="help-block">{{ form.scholarship_type.errors }}</p>
                    {% endif %}
          </div>
          <div class="col-md-4">
            <label>Valid for:</label>
            {{form.school_year|add_class:"form-control"|attr:"placeholder = Enter First Name"}}
                    {% if form.school_year.errors %}
                      <p class="help-block">{{ form.school_year.errors }}</p>
                    {% endif %}
          </div>
        
      </div>
    <div class="btn-forms" style="display: flex; justify-content: flex-end">
      <a href="scholarship-list.html" class="btn btn-link">Cancel</a>
     <input type="submit" class="btn btn-primary" value="Save Scholarship Details"></input>
    </div>
  </form>

front-end/templates/enrollment/table-curriculum-list.html
<table class="table table-bordered bg-nav table-hover">
  <thead class="thead-light">
    <tr>
      <!-- Refer to database for headings -->
      <th scope="col">Curriculum Year</th>
      <th scope="col">Curriculum Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {%for c in curriculum_list%}
    <tr>
      <td>{{c.curriculum_year|date:'Y'}}</td>
      <td>{%if c.get_curriculum_status_display == 'Active'%}<i class="fa fa-circle active-status"></i>{%else%} <i class="fa fa-circle inactive-status"></i>{%endif%}{{c.get_curriculum_status_display}}</td>
      <td class="text-center"><a href="{%url 'curriculum-detail' c.pk %}" class="btn btn-success btn-sm view-button">View</a></td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="5" class="text-center">No Curriculum</td>
    </tr>
    {%endfor%}

  </tbody>
</table>

front-end/templates/enrollment/table-scholarship-list.html
<table class="table table-bordered bg-nav table-hover">
    <thead class="thead-light">
      <tr>
        <!-- Refer to database for headings -->
        <th scope="col">Scholarship ID <i class="fa fa-sort" aria-hidden="true"></th>
        <th scope="col">Scholarship Name <i class="fa fa-sort" aria-hidden="true"></th>
        <th scope="col">Scholarship Type <i class="fa fa-sort" aria-hidden="true"></th>
        <th scope="col">Valid for</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
     {%for s in scholarship_list%}
      <tr>
        <td>{{s.pk}}</td>
        <td>{{s.scholarship_name}}</td>
        <td>{{s.get_scholarship_type_display}}</td>
        <td>{{s.school_year}}</td>
        <td class="text-center"><a href="{% url 'scholarship-update' pk=s.pk %}" class="btn btn-secondary btn-sm view-button">Edit</a></td>
      </tr>
     {% empty %}
        <tr>
          <td colspan="5" class="text-center">No Scholarship</td>
        </tr>
     {%endfor%}
      
    </tbody>
</table>
{% if scholarship_list.has_other_pages %}
<nav aria-label="Page navigation" class="no-print">
  <ul class="pagination pagination-md justify-content-center">
    {% if scholarship_list.has_previous %}
    <li class="page-item">
      <a class="page-link" href="javascript:generatePage({{ scholarship_list.previous_page_number }})" tabindex="-1">Previous</a>
    </li>
    {%else%}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    {%endif%} 
    {% for i in scholarship_list.paginator.page_range %} 
      {% if scholarship_list.number == i %}
        <li class="page-item active"><a class="page-link " href="#" >{{i}}<span class="sr-only">(current)</span></a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="javascript:generatePage({{i}})">{{i}}</a></li>
      {% endif %} 
    {% endfor %} 
    {% if scholarship_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="javascript:generatePage({{ scholarship_list.next_page_number }})">Next</a>
    </li>
    {%else%}
    <li class="page-item disabled">
      <a class="page-link" href="#">Next</a>
    </li>
    {%endif%}
  </ul>
</nav>
{% endif %}